# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HT Love' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HT Love
  #网络数据
  pod 'SwiftyJSON', '~> 4.0'
  pod 'ObjectMapper', '~> 3.3'
  pod 'ReachabilitySwift'
  pod 'Alamofire', '~> 4.7'

  pod 'SnapKit', '~> 4.0.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'SwiftyUserDefaults', '4.0.0-alpha.1'

  #UI
  #pod 'Hero'
  pod 'Hero' , :git => 'https://github.com/HeroTransitions/Hero.git', :commit => '85be93ff80247296ee17f340bef73cfeb18c9fa0'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'RAMAnimatedTabBarController'
  pod 'FoldingCell'
  pod 'NVActivityIndicatorView'
  #pod 'LTMorphingLabel'
  pod 'LTMorphingLabel' , :git => 'https://github.com/lexrus/LTMorphingLabel.git', :commit => 'facd857b77ead0a1c094dfa6634a6e329c6bffff'
  pod 'lottie-ios'

  pod "SkeletonView"
  pod 'TextFieldEffects'
  pod 'SwipeCellKit'

  #swiftInt
  pod 'SwiftLint'

  pod "PromiseKit", "~> 6.0"
  pod 'Moya', '~> 11.0'

  #enxtension
  pod 'SwifterSwift'

  #加密
  pod 'CryptoSwift'

  #leanclound
  #pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
  #pod 'AVOSCloudIM'             # 即时通讯模块
  pod 'LeanCloud'

  #fabric
  pod 'Fabric'
  pod 'Crashlytics'

  target 'HT LoveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HT LoveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
